# Write your MySQL query statement below
SELECT A.MACHINE_ID, round(AVG(B.TIMESTAMP - A.TIMESTAMP),3) AS PROCESSING_TIME
FROM ACTIVITY A
JOIN 
ACTIVITY B
ON 
A.MACHINE_ID = B. MACHINE_ID
AND
A.PROCESS_ID = B. PROCESS_ID
AND
A.TIMESTAMP < B.TIMESTAMP
GROUP BY A.MACHINE_ID

